name: Rive Converter Round-trip Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'converter/**'
      - 'src/**'
      - 'include/**'
      - 'scripts/*.sh'
      - 'scripts/*.py'
      - '.github/workflows/roundtrip.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'converter/**'
      - 'src/**'
      - 'include/**'
      - 'scripts/*.sh'
      - 'scripts/*.py'
      - '.github/workflows/roundtrip.yml'

jobs:
  test-converter:
    name: Converter Round-trip Tests
    runs-on: macos-latest  # macOS for Metal/CoreGraphics support
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        brew install cmake ninja
    
    - name: Configure CMake
      run: |
        cmake -S . -B build_converter \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build Converter Tools
      run: |
        cmake --build build_converter --target json_validator
        cmake --build build_converter --target rive_convert_cli
        cmake --build build_converter --target import_test
        cmake --build build_converter --target universal_extractor
    
    - name: Prepare Test Files
      run: |
        # Ensure output directory exists
        mkdir -p output
        
        # Generate test subsets if bee_baby exists
        if [ -f "converter/exampleriv/bee_baby.riv" ]; then
          mkdir -p output/tests
          
          # Extract full file
          ./build_converter/converter/universal_extractor \
            converter/exampleriv/bee_baby.riv \
            output/tests/bee_baby_NO_TRIMPATH.json
          
          # Create subsets (189/190/273)
          python3 scripts/generate_test_subsets.py output/tests/bee_baby_NO_TRIMPATH.json output/tests
        fi
    
    - name: Run Round-trip Tests
      id: roundtrip
      run: |
        ./scripts/round_trip_ci.sh 2>&1 | tee round_trip_ci.log
      continue-on-error: true
    
    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-outputs
        path: |
          output/**/*.riv
          output/**/*.json
          output/**/*.txt
          round_trip_ci.log
        retention-days: 7
    
    - name: Generate Test Report
      if: always()
      run: |
        echo "## 🧪 Round-trip Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Count test results from log
        PASSED=$(grep -c "ALL TESTS PASSED" round_trip_ci.log 2>/dev/null || echo 0)
        FAILED=$(grep -c "❌ FAILED" round_trip_ci.log 2>/dev/null || echo 0)
        
        echo "### Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Passed: $PASSED" >> $GITHUB_STEP_SUMMARY
        echo "- ❌ Failed: $FAILED" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Add validation details
        echo "### Validation Steps" >> $GITHUB_STEP_SUMMARY
        echo "Each test file goes through:" >> $GITHUB_STEP_SUMMARY
        echo "1. ✅ JSON validation" >> $GITHUB_STEP_SUMMARY
        echo "2. ✅ RIV conversion" >> $GITHUB_STEP_SUMMARY
        echo "3. ✅ Binary structure validation" >> $GITHUB_STEP_SUMMARY
        echo "4. ✅ Stream integrity check" >> $GITHUB_STEP_SUMMARY
        echo "5. ✅ Chunk analysis" >> $GITHUB_STEP_SUMMARY
        echo "6. ✅ Import test" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.roundtrip.outcome }}" == "success" ]; then
          echo "🎉 **All tests passed!**" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ **Some tests failed. Review artifacts for details.**" >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Fail if tests failed
      if: steps.roundtrip.outcome != 'success'
      run: exit 1

  test-validator-standalone:
    name: JSON Validator Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
    
    - name: Configure CMake
      run: |
        cmake -S . -B build_converter \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build Validator
      run: |
        cmake --build build_converter --target json_validator
    
    - name: Test Validator with Test Cases
      run: |
        echo "Testing with empty properties (should fail)..."
        if ./build_converter/converter/json_validator converter/tests/trimpath_empty.json; then
          echo "❌ FAILED: Should have detected empty TrimPath properties"
          exit 1
        else
          echo "✅ PASSED: Correctly detected empty properties"
        fi
        
        echo ""
        echo "Testing with forward reference (should fail)..."
        if ./build_converter/converter/json_validator converter/tests/forward_ref.json; then
          echo "❌ FAILED: Should have detected forward reference"
          exit 1
        else
          echo "✅ PASSED: Correctly detected forward reference"
        fi
        
        echo ""
        echo "✅ All validator unit tests passed"
